apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
namespace: streamlit

images:
- name: app-demo-streamlit
  newName: app-demo-streamlit
  newTag: v1