apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: streamlit

images:
- name: app-demo-streamlit
  newName: sergiopassos/app-demo-streamlit
  newTag: cc5c159eba18f696cd9b7aa08b191b213dc67e5f
