apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: streamlit

images:
- name: app-demo-streamlit
  newName: sergiopassos/app-demo-streamlit
  newTag: 90bb8ef4cceaadaee7f5eec88928adca586e01cd
